{{- if and .Values.database.enabled (not .Values.database.credentials.existingSecret) -}}
{{- $namespace := default .Release.Namespace .Values.namespace.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gestao-financeira.dbFullname" . }}
  namespace: {{ $namespace | quote }}
  labels:
    {{- include "gestao-financeira.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: {{ .Values.database.credentials.rootPassword | quote }}
  MARIADB_DATABASE: {{ .Values.database.credentials.database | quote }}
  MARIADB_USER: {{ .Values.database.credentials.username | quote }}
  MARIADB_PASSWORD: {{ .Values.database.credentials.password | quote }}
{{- end -}}
