{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name | quote }}
  labels:
    {{- include "gestao-financeira.labels" . | nindent 4 }}
{{- end -}}
